[[config]]
name = "Odoo by Adhoc"
odoo_path = "/home/odoo/src/odoo"
python_path = "/usr/local/bin/python"
addons_paths = []

[[config.diagnostic_filters]]
codes = ["OLS.*"]
paths = [
  "/home/odoo/src/*",
]
path_type = "in"
