version: '2.1'
services:
    traefik:
        image: traefik:v1.7.33-alpine
        command:
            - --api
            - --docker
            - --docker.domain=localhost
            - --docker.exposedbydefault=false
        # ports:
        #     - 80:80
        #     - 8080:8080
        labels:
            - traefik.enable=true
            - traefik.port=8080
            - traefik.frontend.rule=Host:traefik.localhost
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
        # para que funcione la solución *.localhost
        network_mode: "host"
