services:

  traefik:
    image: traefik:v2.10.1
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.tcp.address=:5432"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - adhoc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  adhoc:
    name: adhoc
    external: true
